ChgkSystem.WebUI/Controllers/ProtocolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChgkSystem.Domain.Abstract;
using ChgkSystem.Domain.Entities;
using ChgkSystem.WebUI.Models;
using Microsoft.AspNet.Identity;

namespace ChgkSystem.WebUI.Controllers
{
    public class ProtocolController : Controller
    {
		private IUnitOfWork unitOfWork;
		public ProtocolController(IUnitOfWork unitOfWork)
		{
			this.unitOfWork = unitOfWork;
		}

		public ActionResult Modal(int tourID)
		{
			Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == tourID);
			return PartialView("Protocol/_Modal", tour);
		}

		[HttpPost]
	    public ActionResult Check(CheckProtocolFormModel form)
	    {
			if (ModelState.IsValid)
			{
				var userId = User.Identity.GetUserId();
				foreach (var decision in form.Answers)
				{
					var answerId = Convert.ToInt32(decision.Key);
					var answer =
						unitOfWork.AnswerRepository.FindOneBy(
							a => a.ID == answerId && a.Decisions.All(d => d.UserID != userId));
					if (answer == null)
					{
						return Json(new {status = "Error"});
					}
					answer.Decisions.Add(new AnswerDecision
					{
						Decision = decision.Value,
						UserID = userId
					});
					if (answer.Decisions.Count(a => a.Decision == decision.Value) == answer.Question.Tour.Tournament.Jury.Count
					    && answer.Status == AnswerStatus.Pending)
					{
						answer.Status = (decision.Value == JuryDecision.Correct) ? AnswerStatus.Correct : AnswerStatus.Incorrect;
					}
				}
				unitOfWork.Save();
				if (!unitOfWork.AnswerRepository.FindBy(m => m.Question.TourID == form.TourID && m.Status == AnswerStatus.Pending).Any())
				{
					Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == form.TourID);
					tour.Status = TourStatus.WaitingAppeals;
					unitOfWork.TourRepository.Edit(tour);
				}
				return Json(new { status = "OK" });
			}
			else
			{
				Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == form.TourID);
				return PartialView("Protocol/_Modal", tour);
			}
	    }

	    public ActionResult Discuss(DiscussProtocolFormModel form)
	    {
		    throw new NotImplementedException();
	    }
    }
}

ChgkSystem.WebUI/Views/Shared/Protocol/_AddFileForm.cshtml
<label for="inputResultFile">Загрузить обработанный файл</label>
<div class="btn-group">
	<div class="row">
		<div class="col-sm-9">
			<input id="File" type="file" class="filestyle" data-buttontext="Выбрать файл" data-buttonbefore="true">
		</div>
		<div class="col-sm-3">
			<button type="button" class="btn btn-primary btn-block">Загрузить</button>
		</div>
	</div>
</div>

ChgkSystem.WebUI/Views/Shared/Protocol/_CheckForm.cshtml
@using ChgkSystem.Domain.Entities
@using Microsoft.AspNet.Identity
@model ChgkSystem.WebUI.Models.CheckProtocolFormModel

@{
	AjaxOptions ajaxOptions = new AjaxOptions
	{
		HttpMethod = "POST",
		OnSuccess = "onSuccessGeneric"
	};
}

@using (Ajax.BeginForm("Check", "Protocol", ajaxOptions))
{
	@Html.HiddenFor(m => m.TourID)
	<div class="modal-body">
		@foreach (var question in Model.Questions)
		{
			var answers = question.PendingAnswers.Where(a => a.Decisions.All(d => d.UserID != User.Identity.GetUserId()));
			if (!answers.Any())
			{
				continue;
			}
			<label>@question.Text</label>
			foreach (var answer in answers)
			{
				<div class="row">
					<div class="col-sm-8">
						@answer.Text
					</div>
					<div class="col-sm-4 check-buttons">
						<div class="btn-group" data-toggle="buttons">
							<label class="btn btn-default btn-sm">
								@Html.RadioButton("Answers[" + answer.ID + "]", JuryDecision.Incorrect)
								<input type="radio" name="options" id="option1">
								<span class="text-danger">
									<i class="fa fa-times"></i>
									Неверно
								</span>
							</label>
							<label class="btn btn-default btn-sm">
								@Html.RadioButton("Answers[" + answer.ID + "]", JuryDecision.Correct)
								<span class="text-success">
									<i class="fa fa-check"></i>
									Верно
								</span>
							</label>
						</div>
					</div>
				</div>
				<hr />
			}
		}
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
		<input type="submit" class="btn btn-primary" value="Сохранить">
	</div>
}

ChgkSystem.WebUI/Views/Shared/Protocol/_DiscussForm.cshtml
@using ChgkSystem.Domain.Entities
@model ChgkSystem.WebUI.Models.DiscussProtocolFormModel

@{
	AjaxOptions ajaxOptions = new AjaxOptions
	{
		HttpMethod = "POST",
		OnSuccess = "onSuccessGeneric"
	};
}

@using (Ajax.BeginForm("Discuss", "Protocol", ajaxOptions))
{
	@Html.HiddenFor(m => m.TourID)
	<div class="modal-body">
		@foreach (var question in Model.Questions)
		{
			var answers = question.PendingAnswers.Where(a => a.Decisions.Select(d => d.Decision).Distinct().Count() > 1);
			if (!answers.Any())
			{
				continue;
			}
			<label>@question.Text</label>
			foreach (var answer in answers)
			{
				<div class="row">
					<div class="col-sm-8">
						@answer.Text

						<div>
							<a href="#" data-toggle="collapse" data-target="@("#discuss" + answer.ID)">
								<i class="fa fa-comments-o"></i>
								Мнения
							</a>
							<ul id="@("#discuss" + answer.ID)" class="list-unstyled list-tabbed collapse">
								@foreach (var decision in answer.Decisions)
								{
									<li>
										@switch (decision.Decision)
										{
											case JuryDecision.Correct:
												<span class="text-success">
												<i class="fa fa-check"></i>
												@decision.User.UserName считает ответ верным
											</span>
												break;
											case JuryDecision.Incorrect:
												<span class="text-danger">
												<i class="fa fa-times"></i>
												@decision.User.UserName считает ответ неверным
											</span>
												break;
										}
									</li>
								}
							</ul>
						</div>
					</div>
					<div class="col-sm-4 check-buttons">
						<div class="btn-group" data-toggle="buttons">
							<label class="btn btn-default btn-sm">
								@Html.RadioButton("Answers[" + answer.ID + "]", JuryDecision.Incorrect)
								<input type="radio" name="options" id="option1">
								<span class="text-danger">
								<i class="fa fa-times"></i>
								Неверно
							</span>
							</label>
							<label class="btn btn-default btn-sm">
								@Html.RadioButton("Answers[" + answer.ID + "]", JuryDecision.Correct)
								<span class="text-success">
								<i class="fa fa-check"></i>
								Верно
							</span>
							</label>
						</div>
					</div>
				</div>
				<hr/>
			}
		}
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
		<input type="submit" class="btn btn-primary" value="Сохранить">
	</div>
}

ChgkSystem.WebUI/Views/Shared/Protocol/_Modal.cshtml
@using ChgkSystem.WebUI.Models
@model ChgkSystem.Domain.Entities.Tour

<ul class="nav nav-tabs" id="checkProtocolTab">
	@*<li class="active"><a href="#protocol-file" data-toggle="tab">Из файла</a></li>*@
	<li><a href="#protocol-form" data-toggle="tab">Заполнить форму</a></li>
	<li><a href="#protocol-discuss" data-toggle="tab">Спорные ответы</a></li>
</ul>
<div class="tab-content">
	@*<div class="tab-pane active" id="protocol-file">
		<div class="modal-body">
			<div class="form-group">
				<label><a>Скачать файл с протоколом</a></label>
			</div>
			<div class="form-group">
				@Html.Partial("Protocol/_AddFileForm")
			</div>
		</div>
	</div>*@
	<div class="tab-pane active" id="protocol-form">
		@Html.Partial("Protocol/_CheckForm", new CheckProtocolFormModel { TourID = Model.ID, Questions = Model.Questions })
	</div>
	<div class="tab-pane" id="protocol-discuss">
		@Html.Partial("Protocol/_DiscussForm", new DiscussProtocolFormModel { TourID = Model.ID, Questions = Model.Questions })
	</div>
</div>