ChgkSystem.WebUI/Models/AppealsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ChgkSystem.Domain.Entities;

namespace ChgkSystem.WebUI.Models
{
	public class AppealsViewModel
	{
		public int TourID { get; set; }

		public IEnumerable<Appeal> Appeals { get; set; }
		public string AppealsText { get; set; }
	}
}

ChgkSystem.WebUI/Controllers/AppealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChgkSystem.Domain.Abstract;
using ChgkSystem.Domain.Entities;
using ChgkSystem.WebUI.Models;

namespace ChgkSystem.WebUI.Controllers
{
    public class AppealController : Controller
    {
		private IUnitOfWork unitOfWork;
		public AppealController(IUnitOfWork unitOfWork)
		{
			this.unitOfWork = unitOfWork;
		}

	    [HttpGet]
	    public ActionResult Add(int tourID)
	    {
		    Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == tourID);
		    AddAppealFormModel model = new AddAppealFormModel
		    {
				Tour = tour,
				TourID = tourID,
				Appeal = new Appeal()
		    };
			return PartialView("Appeal/_AddForm", model);
	    }

		[HttpPost]
		public ActionResult Add(AddAppealFormModel form)
		{
			if (ModelState.IsValid)
			{
				unitOfWork.AppealRepository.Add(form.Appeal);
				//string url = Url.Action("details", "tournament", new { ID = form. }) + "#tours";
				return Json(new { status = "OK" });
			}
			form.Tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == form.TourID);
			return PartialView("Appeal/_AddForm", form);
		}

	    public ActionResult List(int tourID)
		{
			Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == tourID);
		    AppealsViewModel model = new AppealsViewModel
		    {
				TourID = tourID,
			    Appeals = tour.Appeals.Where(m => m.AppealStatus == AppealStatus.Pending),
			    AppealsText = "asdasd"
		    };
			return PartialView("Appeal/_List", model);

	    }

	    [HttpPost]
	    public ActionResult Review(AppealReviewFormModel form)
	    {
		    foreach (var review in form.Reviews)
		    {
				int appealId = int.Parse(review.Key);
				var appeal = unitOfWork.AppealRepository.FindOneBy(m => m.ID == appealId);
			    if (review.Value == AppealStatus.Accepted)
			    {
				    if (appeal.AppealType == AppealType.AnswerAccept)
				    {
					    appeal.Answer.Status = AnswerStatus.Correct;
				    } 
					else if (appeal.AppealType == AppealType.QuestionDecline)
					{
						appeal.Question.IsIncorrect = true;
					}
			    }
			    appeal.AppealStatus = review.Value;
				unitOfWork.AppealRepository.Edit(appeal);
		    }
		    Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == form.TourID);
		    if (tour.Appeals.All(m => m.AppealStatus != AppealStatus.Pending) && tour.ApealsUntilDate < DateTime.Now)
		    {
			    tour.Status = TourStatus.Finished;
		    }
			return Json(new { status = "OK" });
	    }
    }
}

ChgkSystem.WebUI/Views/Shared/Appeal/_AddForm.cshtml
@using ChgkSystem.Domain.Entities
@model ChgkSystem.WebUI.Models.AddAppealFormModel

@{
	AjaxOptions ajaxOptions = new AjaxOptions
	{
		HttpMethod = "POST",
		OnSuccess = "onSuccessGeneric"
	};
}

@using (Ajax.BeginForm("Add", "Appeal", ajaxOptions))
{
	<div class="modal-body">
		<div class="form-group">
			@Html.LabelFor(m => m.Appeal.TeamID)
			@Html.DropDownListFor(m => m.Appeal.TeamID, new SelectList(Model.Tour.Tournament.Teams, "ID", "Name"), "Выберите команду", new { @class = "form-control" })
			@Html.ValidationMessageFor(m => m.Appeal.TeamID)
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Appeal.QuestionID)
			@Html.DropDownListFor(m => m.Appeal.QuestionID, new SelectList(Model.Tour.Questions, "ID", "Text"), "Выберите вопрос", new { @class = "form-control" })
			@Html.ValidationMessageFor(m => m.Appeal.QuestionID)
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Appeal.AppealType)
			<div class="radio">
				<label>
					@Html.RadioButtonFor(m => m.Appeal.AppealType, AppealType.QuestionDecline)
					Снятие вопроса
				</label>
			</div>
			<div class="radio">
				<label>
					@Html.RadioButtonFor(m => m.Appeal.AppealType, AppealType.QuestionDecline)
					Зачет ответа
				</label>
			</div>
			@Html.ValidationMessageFor(m => m.Appeal.AppealType)
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Appeal.Text)
			@Html.TextAreaFor(m => m.Appeal.Text, new { @class = "form-control" })
			@Html.ValidationMessageFor(m => m.Appeal.Text)
		</div>
		<hr/>
		<div class="form-group">
			@Html.LabelFor(m => m.Appeal.Email)
			@Html.TextBoxFor(m => m.Appeal.Email, new { @class = "form-control" })
			@Html.ValidationMessageFor(m => m.Appeal.Email)
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
		<input type="submit" class="btn btn-primary" value="Добавить">
	</div>
}

ChgkSystem.WebUI/Views/Shared/Appeal/_Item.cshtml
@model ChgkSystem.Domain.Entities.Appeal

<div class="apeal-review">
	<div class="btn-group pull-right" data-toggle="buttons">
		<label class="btn btn-default btn-sm">
			<input type="radio" name="options" id="option1">
			<span class="text-danger">
				<i class="fa fa-times"></i>
				Отклонить
			</span>
		</label>
		<label class="btn btn-default btn-sm">
			<input type="radio" name="options" id="option2">
			<span class="text-success">
				<i class="fa fa-check"></i>
				Принять
			</span>
		</label>
	</div>
	<ul class="list-unstyled">
		<li>
			<label>Команда:</label>
			@Model.Team.Name
		</li>
		<li>
			<label>Вопрос:</label>
			@Model.Question.Text
		</li>
		<li><label>Ответ:</label> Какой-то текст ответа</li>
		<li><label>Тип апелляции:</label> Снятие вопроса</li>
		<li>
			<label>Аргументация</label>
			<br />
			Ut fusce varius nisl ac ipsum gravida vel pretium tellus tincidunt integer eu augue augue nunc elit dolor, luctus placerat.

		</li>
	</ul>
</div>

ChgkSystem.WebUI/Views/Shared/Appeal/_List.cshtml
@using ChgkSystem.WebUI.Models
@model AppealsViewModel
		   
<ul class="nav nav-tabs" id="myTab">
	<li class="active"><a href="#apealList" data-toggle="tab">Список поданных апелляций</a></li>
	<li><a href="#apealReview" data-toggle="tab">Рассмотрение апелляций</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="apealList">
		<div class="modal-body">
			<div class="form-group">
				<label for="appealsText">Текст апелляций</label>
				<textarea id="appealsText" class="form-control" rows="6">@Model.AppealsText</textarea>
				<span class="help-block"><a href="#">Скачать в виде текстового файла</a></span>
			</div>
		</div>
	</div>
	<div class="tab-pane" id="apealReview">
		@Html.Partial("Appeal/_ReviewForm", new AppealReviewFormModel { Appeals = Model.Appeals, TourID = Model.TourID })
	</div>
</div>

ChgkSystem.WebUI/Views/Shared/Appeal/_ReviewForm.cshtml
@using ChgkSystem.Domain.Entities
@model ChgkSystem.WebUI.Models.AppealReviewFormModel

@{
	AjaxOptions ajaxOptions = new AjaxOptions
	{
		HttpMethod = "POST",
		OnSuccess = "onSuccessGeneric"
	};
}

@using (Ajax.BeginForm("Review", "Appeal", ajaxOptions))
{
	@Html.HiddenFor(m => m.TourID)
	<div class="modal-body">
		@foreach (var appeal in Model.Appeals)
		{
			<div class="apeal-review">
				<div class="btn-group pull-right" data-toggle="buttons">
					<label class="btn btn-default btn-sm">
						@Html.RadioButton("Reviews[" + appeal.ID.ToString() + "]", AppealStatus.Rejected)
						<span class="text-danger">
							<i class="fa fa-times"></i>
							Отклонить
						</span>
					</label>
					<label class="btn btn-default btn-sm">
						@Html.RadioButton("Reviews[" + appeal.ID.ToString() + "]", AppealStatus.Accepted)
						<span class="text-success">
							<i class="fa fa-check"></i>
							Принять
						</span>
					</label>
				</div>
				<ul class="list-unstyled">
					<li>
						<label>Команда:</label>
						@appeal.Team.Name
					</li>
					<li>
						<label>Вопрос:</label>
						@appeal.Question.Text
					</li>
					<li>
						@if (appeal.Answer != null)
						{
							<label>Ответ:</label>
							@appeal.Answer.Text
						}
						else
						{
							<label>Вопрос не отвечен</label>
						}
					</li>
					<li>
						<label>Тип апелляции:</label>
						@switch (appeal.AppealType)
						{
							case AppealType.AnswerAccept:
								@:Зачет ответа
								break;
							case AppealType.QuestionDecline:
								@:Снятие вопроса
								break;
						}
					</li>
					<li>
						<label>Аргументация</label>
						<br/>
						@appeal.Text
					</li>
				</ul>
			</div>
			<hr/>
		}
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
		<input type="submit" class="btn btn-primary" value="Сохранить">
	</div>
}