ChgkSystem.WebUI/Controllers/GroupController.cs
using System.Web.Mvc;
using ChgkSystem.Domain.Abstract;
using ChgkSystem.Domain.Entities;
using Microsoft.AspNet.Identity;

namespace ChgkSystem.WebUI.Controllers
{
    public class GroupController : Controller
    {
		private IUnitOfWork unitOfWork;
		public GroupController(IUnitOfWork unitOfWork)
		{
			this.unitOfWork = unitOfWork;
		}

		[HttpPost]
		[Authorize(Roles = "Managers, Administrators")]
		public ActionResult Add(Group group)
		{
			if (ModelState.IsValid)
			{
				Tournament t = unitOfWork.TournamentRepository.FindOneBy(m => m.ID == group.TournamentID);
				if (t.UserID != HttpContext.User.Identity.GetUserId())
				{
					return Json(new { status = "Error" });
				}
				t.Groups.Add(group);
				unitOfWork.TournamentRepository.Edit(t);
				string url = Url.Action("details", "tournament", new { ID = t.ID }) + "#groups";
				return Json(new { status = "OK", url = url });
			}
			else
			{
				return PartialView("Group/_AddForm", group);
			}
		}
    }
}

ChgkSystem.WebUI/Views/Shared/Group/_AddForm.cshtml
@model ChgkSystem.Domain.Entities.Group

@{
	AjaxOptions ajaxOptions = new AjaxOptions
	{
		HttpMethod = "POST",
		OnSuccess = "onSuccessGeneric"
	};
}

@using (Ajax.BeginForm("Add", "Group", ajaxOptions))
{
	@Html.HiddenFor(m => m.TournamentID)
	<div class="modal-body">
		<div class="form-group">
			@Html.LabelFor(m => m.Title)
			@Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
			@Html.ValidationMessageFor(m => m.Title)
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Description)
			@Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = 6 })
			@Html.ValidationMessageFor(m => m.Description)
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
		<input type="submit" class="btn btn-primary" value="Добавить">
	</div>
}