ChgkSystem.WebUI/Controllers/QuestionsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using ChgkSystem.Domain.Abstract;
using ChgkSystem.Domain.Entities;
using ChgkSystem.Parsers;
using ChgkSystem.WebUI.Models;
using Microsoft.AspNet.Identity;

namespace ChgkSystem.WebUI.Controllers
{
    public class QuestionsController : Controller
    {
		private IUnitOfWork unitOfWork;
	    private IQuestionsFileParser parser;
		public QuestionsController(IUnitOfWork unitOfWork, IQuestionsFileParser parser)
		{
			this.unitOfWork = unitOfWork;
			this.parser = parser;
		}

		[HttpPost]
		[Authorize(Roles = "Managers, Administrators")]
		public ActionResult AddFile(QuestionsFileModel form)
		{
			if (ModelState.IsValid)
			{
				List<Question> questions = parser.Parse(form.File.InputStream);
				Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == form.TourID);
				if (tour.Tournament.UserID != HttpContext.User.Identity.GetUserId())
				{
					return Json(new { status = "Error" });
				}
				tour.Questions = questions;
				unitOfWork.TourRepository.Edit(tour);
				string url = Url.Action("details", "tournament", new { ID = tour.TournamentID }) + "#tours";
				return Json(new { status = "OK", url = url });
			}
			else
			{
				return Json(new { status = "Error" });
			}
		}

	    [HttpGet]
	    [Authorize(Roles = "Managers, Administrators")]
	    public ActionResult EditVisibility(int tourID)
	    {
			Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == tourID);
		    QuestionsVisibilityFormModel model = new QuestionsVisibilityFormModel
		    {
			    QuestionsVisibility = tour.QuestionsVisibility,
			    TourID = tourID
		    };
			return PartialView("Questions/_VisibilityForm", model);
	    }

		[HttpPost]
		[Authorize(Roles = "Managers, Administrators")]
	    public ActionResult EditVisibility(QuestionsVisibilityFormModel form)
	    {
			if (ModelState.IsValid)
			{
				Tour tour = unitOfWork.TourRepository.FindOneBy(m => m.ID == form.TourID);
				tour.QuestionsVisibility = form.QuestionsVisibility;
				unitOfWork.TourRepository.Edit(tour);
				string url = Url.Action("details", "tournament", new { ID = tour.TournamentID }) + "#tours";
				return Json(new { status = "OK", url = url });
			}
			else
			{
				return PartialView("Questions/_VisibilityForm");
			}
	    }
    }
}

ChgkSystem.WebUI/Views/Shared/Questions/_AddFileForm.cshtml
@model ChgkSystem.WebUI.Models.QuestionsFileModel

@using (Html.BeginForm("AddFile", "Questions", FormMethod.Post, new { enctype = "multipart/form-data", id = "addQuestionsFileForm" }))
{
	@Html.HiddenFor(m => m.TourID)
	<div class="modal-body">
		<div class="btn-group">
			<div class="row">
				<div class="col-sm-9">
					@Html.TextBoxFor(m => m.File, new { type = "file", @class = "filestyle", data_buttontext = "Выбрать файл", data_buttonbefore = "true", id = "questionsFileInput" })
					@Html.ValidationMessageFor(m => m.File)
				</div>
				<div class="col-sm-3">
					<button type="submit" class="btn btn-primary btn-block">Загрузить</button>
				</div>
			</div>
		</div>
	</div>
}

ChgkSystem.WebUI/Views/Shared/Questions/_AddForm.cshtml
<div class="modal-body">
	<form role="form">
		<div class="question-form">
			<div class="form-group">
				<label for="question1">Вопрос</label>
				<input type="text" class="form-control" id="questionName1">
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="form-group">
						<label for="trueAnswers1">Верные ответы</label>
						<textarea id="trueAnswers1" class="form-control" rows="3"></textarea>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="trueAnswers1">Неверные ответы</label>
						<textarea id="trueAnswers1" class="form-control" rows="3"></textarea>
					</div>
				</div>
			</div>
			<hr />
		</div>
		<button type="button" class="btn btn-link" id="addQuestionButton">Добавить вопрос</button>
	</form>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
	<input type="submit" class="btn btn-primary" value="Добавить">
</div>

ChgkSystem.WebUI/Views/Shared/Questions/_AddLinkedTourForm.cshtml
<div class="modal-body">
	linked
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
	<input type="submit" class="btn btn-primary" value="Добавить">
</div>

ChgkSystem.WebUI/Views/Shared/Questions/_VisibilityForm.cshtml
@using ChgkSystem.Domain.Entities
@model ChgkSystem.WebUI.Models.QuestionsVisibilityFormModel

@{
	AjaxOptions ajaxOptions = new AjaxOptions
	{
		HttpMethod = "POST",
		OnSuccess = "onSuccessGeneric"
	};
}

@using (Ajax.BeginForm("EditVisibility", "Questions", ajaxOptions))
{
	@Html.HiddenFor(m => m.TourID)
	<div class="modal-body">
		<div class="form-group">
			<label>Вопросы видны для</label>
			<div class="radio">
				<label>
					@Html.RadioButtonFor(m => m.QuestionsVisibility, QuestionsVisibility.ForMe)
					Меня
				</label>
			</div>
			<div class="radio">
				<label>
					@Html.RadioButtonFor(m => m.QuestionsVisibility, QuestionsVisibility.ForPlaygroundManager)
					<input type="radio" value="" name="appealType">
					Организаторов отчетных площадок
				</label>
			</div>
			<div class="radio">
				<label>
					@Html.RadioButtonFor(m => m.QuestionsVisibility, QuestionsVisibility.ForAll)
					Всех
				</label>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
		<input type="submit" class="btn btn-primary" value="Добавить">
	</div>
}